### ISSUE TITLE
Noob biff example app

### ISSUE THREAD

**Issue by soex201** [jacobobryant/biff-code-review#1]
Hi, 

I've create biff [example](https://github.com/soex201/biffr) app, it's based on python flaskr. Could you take a look? thank you.

**Comment by jacobobryant** [comment]
Sure! I just looked through it. I don't think it's in need of any major changes; it looks quite good. So here are some stylistic suggestions, some of which may be my own personal preference:

- Use `pull` instead of `:where` when possible

For example, [get-posts](https://github.com/soex201/biffr/blob/main/src/com/example/feat/app.clj#L8) currently looks like this:

```clojure
(defn get-posts 
  [db]
  (biff/q db 
    '{:find [id title body email time]
      :keys [post-id post-title post-body post-author post-time]
      :where [[id :post/title title]
              [id :post/body body]
              [id :post/created time]
              [id :post/user author-id]
              [author-id :user/email email]]
      :order-by [[time :desc]]}))
```

You can simplify it to this:

```clojure
(defn get-posts 
  [db]
  (->> (biff/q db 
               '{:find (pull post [* {:post/user [*]}])
                 :where [[post :post/title]]})
       (sort-by :post/created #(compare %2 %1))))
```

You would need to also change [render-post](https://github.com/soex201/biffr/blob/31a4663f30f62047a359ef15c59859c1b1fa0ca8/src/com/example/feat/app.clj#L117) from this:

```clojure
(defn render-post
  [{:keys [post-id post-title post-body post-author post-time]} email]
  [:article.post {:id (str "post-" post-id)}
   [:header
    [:div
     [:h1 post-title]
     [:div.about (str "by " (first (clojure.string/split post-author #"@")) " on " post-time)]]
    (if email 
      [:a.action {:hx-get (str "/app/update/" post-id)
                  :hx-target (str "#post-" post-id)
                  :hx-swap "outerHTML"} "Edit"])]
   [:p.body post-body]])
```

to this:

```clojure
(defn render-post
  [{:post/keys [title body user created] :keys [xt/id]} email]
  [:article.post {:id (str "post-" id)}
   [:header
    [:div
     [:h1 title]
     [:div.about (str "by " (first (clojure.string/split (:user/email user) #"@")) " on " created)]]
    (if email 
      [:a.action {:hx-get (str "/app/update/" id)
                  :hx-target (str "#post-" id)
                  :hx-swap "outerHTML"} "Edit"])]
   [:p.body body]])
```

I would make a similar change to [get-post](https://github.com/soex201/biffr/blob/31a4663f30f62047a359ef15c59859c1b1fa0ca8/src/com/example/feat/app.clj#L20). In that case, since you have a specific document ID already, you can use `xtdb.api/pull` instead of `q`.

Nitpicks:

 - Change [`(get-post id node)`](https://github.com/soex201/biffr/blob/31a4663f30f62047a359ef15c59859c1b1fa0ca8/src/com/example/feat/app.clj#L205) to `(get-post id (xt/db node))`. Then `get-post` can remain a pure function.
 - Instead of calling `clojure.string/split`, add `[clojure.string :as str]` to your list of requires at the top of the namespace and then call `str/split`.
 - No need to call [`biff/render`](https://github.com/soex201/biffr/blob/31a4663f30f62047a359ef15c59859c1b1fa0ca8/src/com/example/feat/app.clj#L180).   Biff comes with [some middleware](https://github.com/soex201/biffr/blob/31a4663f30f62047a359ef15c59859c1b1fa0ca8/src/com/example.clj#L21) that will call `biff/render` for you if the handler returns a vector (in which case we assume it's a hiccup vector).

**Comment by soex201** [comment]
Hi, wow thank you so much for detail review. It really helps a learner like me.

**Comment by jacobobryant** [comment]
Any time!
